# Generated by Django 6.0.2 on 2026-02-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_role_user_user_type_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=20),
        ),
    ]
