# Generated by Django 6.0.2 on 2026-02-24 10:41

import users.models
from django.db import migrations, models


def set_default_user_type(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(user_type='').update(user_type='patient')
    User.objects.filter(user_type__isnull=True).update(user_type='patient')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.RunPython(set_default_user_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=10),
        ),
    ]
