# Generated by Django 6.0.2 on 2026-03-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_managers_alter_user_user_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('doctor', 'date', 'time'), name='uniq_active_doctor_slot'),
        ),
    ]
