name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          black --check apps backend tests scripts
          flake8 apps backend tests scripts
          mypy apps backend tests scripts

      - name: Django Checks
        env:
          DJANGO_SETTINGS_MODULE: curamind_core.settings
          DJANGO_ENV: test
        run: |
          python backend/django_core/manage.py check --settings=curamind_core.settings.test
          python backend/django_core/manage.py spectacular --file schema.yml --validate --settings=curamind_core.settings.test

      - name: Tests
        env:
          DJANGO_SETTINGS_MODULE: curamind_core.settings
          DJANGO_ENV: test
        run: |
          pytest --cov --cov-report=term --cov-report=xml --cov-fail-under=90
